Fixes encoding issues
Shopify/spoom pull request #52
Opened 2020-11-27 16:06 UTC by masylum

While running certain commands, spoom was chocking with some of our files containing € signs.

2020-11-27 16:53 UTC, Morriar requested changes
👋 @masylum, 

Good catch, thanks a lot for the fix!

Can you add tests in https://github.com/Shopify/spoom/blob/master/test/spoom/sorbet/sigils_test.rb showing the behaviours for `file_strictness` and `change_sigil_in_file` please?

2020-12-15 10:00 UTC, masylum commented
Hey @Morriar, any feedback?

2020-12-16 15:31 UTC, Morriar requested changes
👋 @masylum,

I'm not sure this is the right approach.

This still reads the file with the wrong encoding, then saves it as UTF8 once the sigil bump is done. This might create issues for the user where we'll silently recode their files.

Also, the provided test doesn't use external files, so it doesn't really reproduce the original issue you were having.

I proposed another fix for this issue in https://github.com/Shopify/spoom/pull/56, let me know if it works for you. In the mean time, I'm closing this PR.

2020-12-16 15:31 UTC, Morriar commented on test/spoom/sorbet/sigils_test.rb
> +        strictness = Sigils.strictness_in_content(content.dup.force_encoding("ISO-8859-1"))
Why not something like `"€".encode("ISO-8859-15")` so it's easier to read?

2020-12-16 15:31 UTC, Morriar commented on test/spoom/sorbet/sigils_test.rb
> +          "#{[0x89].pack('c*')}"
Can we have a comment indicating which character this is supposed to represent?

2020-12-16 15:31 UTC, Morriar commented on lib/spoom/sorbet/sigils.rb
> +        content = File.read(path, encoding: 'UTF-8')
Will this solve the problem? We're still reading an ISO file as UTF8?

Furthermore, would that mean we'll save the file as UTF after the bump? Silently re-encoding users files might not be the best approach here.

2020-12-16 15:31 UTC, closed without merging